In [1]:
import numpy as np

a1 = np.arange(1,11)
a2 = np.arange(1,10).reshape(3,3)
a3 = np.zeros((4,4))
a4 = np.ones((2,5))

print(a1)
print(a2)
print(a3)
print(a4)

[ 1  2  3  4  5  6  7  8  9 10]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [2]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.ndim)

(2, 3)
6
int64
2


In [3]:
arr = np.array([10,20,30,40,50,60])

print(arr[0])
print(arr[-1])
print(arr[2])

print(arr[arr>30])

10
60
30
[40 50 60]


In [4]:
arr = np.array([10,20,30,40,50,60])

print(arr[1:5])
print(arr[::-1])
print(arr[::2])

m = np.arange(1,10).reshape(3,3)

print(m[0])
print(m[:,1])
print(m[1:])

[20 30 40 50]
[60 50 40 30 20 10]
[10 30 50]
[1 2 3]
[2 5 8]
[[4 5 6]
 [7 8 9]]


In [5]:
arr = np.array([1,2,3,4,5])

print(arr*5)
print(arr+10)
print(arr**2)

[ 5 10 15 20 25]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [6]:
arr = np.arange(1,7).reshape(2,3)

print(arr+10)
print(arr*2)

[[11 12 13]
 [14 15 16]]
[[ 2  4  6]
 [ 8 10 12]]


In [7]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(a+b)
print(a-b)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [8]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print(np.dot(a,b))
print(a.T)

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]


In [9]:
r1 = np.random.randint(1,101,(4,4))
r2 = np.random.rand(4,4)

print(r1)
print(r2)

print(r1.max())
print(r1.min())
print(r1.mean())

[[35 64 48 15]
 [13 72 27 71]
 [48 45 16 88]
 [ 2  6 89 37]]
[[0.68749801 0.98269057 0.59500946 0.65582202]
 [0.95823018 0.98711988 0.13304589 0.09343094]
 [0.2208702  0.25935195 0.12731845 0.36630271]
 [0.1836645  0.80108949 0.23984794 0.62410851]]
89
2
42.25


In [10]:
marks = np.array([45,67,89,90,55,78,82,49,60,95])

print(marks.mean())
print(marks.max())
print(marks.min())

print(len(marks[marks>80]))
print(marks[marks<50])

71.0
95
45
4
[45 49]


In [11]:
img = np.random.randint(0,256,(5,5))

print(img)
print(img.max())
print(img.min())
print(img.shape)

[[147 137  50 199  91]
 [ 71  14 225   8 194]
 [ 28 105  53  75 154]
 [ 93 243 119  41  99]
 [239 210 152 235  58]]
243
8
(5, 5)


In [12]:
data = np.array([10,20,30,40,50])

norm = (data - data.min()) / (data.max() - data.min())

print(norm)

[0.   0.25 0.5  0.75 1.  ]


In [13]:
data = np.array([
    [22,25000,0],
    [25,30000,1],
    [30,40000,1],
    [35,50000,1],
    [28,27000,0]
])

X = data[:,:2]
y = data[:,2]

print(X)
print(y)

print(X[:,1].mean())
print(X[:,0].max())
print(data.shape)

[[   22 25000]
 [   25 30000]
 [   30 40000]
 [   35 50000]
 [   28 27000]]
[0 1 1 1 0]
34400.0
35
(5, 3)
